### ISSUE TITLE
env['omniauth.params'] and env['omniauth.origin'] not passed through when using custom full_host

### ISSUE THREAD

**Issue by dangerp** [intridea/omniauth#608]
This issue is more fully articulated here: http://stackoverflow.com/q/10643847/847377

An example app using omniauth 1.1.0 is here: https://github.com/dangerp/omniauth_origin_example

Using a simple test (see sample app above), I am able to pull `env['omniauth.params']` and `env['omniauth.origin']` from the request after the browser is directed to the callback URL.  However, if I have the user directed to a custom URL using `OmniAuth.config.full_host`, those variables are there, but they are empty.  Any ideas on why this is happening, or what I can do to obtain the origin URL?

**Comment by xinspire** [comment]
@cawel I have the same use case in 2016, and I'm wondering what you ended up doing.  I'm guessing by the issue closure date that OmniAuth does not support this at this time.  I'm using omniauth for LinkedIn instead of Google, and they have a limit of 50 `redirect_uri`s.
