### ISSUE TITLE
OpenID2 for Google accounts is going away on April 20, 2015

### ISSUE THREAD

**Issue by trueinviso** [intridea/omniauth#787]
I can't seem to find anything about migrating away from openid for omniauth users?  Is this as simple as changing the redirect url?

`require "openid/store/filesystem"`
`require "omniauth-google-oauth2"`
`config.omniauth :google_apps,`
    `store: OpenID::Store::Filesystem.new('/tmp'),`
    `domain: "example.com",` 
    `identifier: "https://www.google.com/accounts/o8/id"`

**Comment by mbleigh** [comment]
This is a specific strategy question and would be best asked on the strategy repo.
