### ISSUE TITLE
Does omniauth support Ruby 2.2?

### ISSUE THREAD

**Issue by dqdinh** [intridea/omniauth#803]
The README does not mention Ruby 2.2 but Ruby 2.2 was added to the Travis CI test matrix (https://github.com/intridea/omniauth/commit/46938eb5a7539ff1794c7c6f5fd438acc7e4b272) so I assume is supported. There is also a pull request (https://github.com/intridea/omniauth/pull/797).

**Comment by afeld** [comment]
* [ ] Add to [the list of supported ruby versions](https://github.com/intridea/omniauth#supported-ruby-versions)

**Comment by ragesoss** [comment]
I'm using omniauth with Ruby 2.3 in production, and have not run into any problems.
