### ISSUE TITLE
Keeps redirecting to Register, even with user found in Database

### ISSUE THREAD

**Issue by simkessy** [intridea/omniauth#816]
I've trying to set up Devise and Omniauth in my application. I signed up with Facebook, but it always redirects me to the user registration page. The first time it happens, it's not the worst thing since I need additional information that Facebook doesn't provide. But when I logout and try to sign in again with the Facebook link, it sends me again to the registration page, which doesn't work since the email is already used. 

The server log shows that it's already found the user but still sends me to register. 

    User Load (1.4ms)  SELECT  "users".* FROM "users" WHERE "users"."provider" = $1 AND "users"."uid" = $2  ORDER BY "users"."id" ASC LIMIT 1  [["provider", "facebook"], ["uid", "10153022752496134"]]
       (0.3ms)  BEGIN
      User Exists (0.7ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = '["simkessy@gmail.com", "hyqtm4nc_ms4grsu4_r1"]' LIMIT 1
       (0.9ms)  ROLLBACK
    Redirected to http://localhost:3000/register
    Completed 302 Found in 70ms (ActiveRecord: 3.4ms)

This is my user.rb:

    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
          user.email = auth.info.email,
          user.password = Devise.friendly_token[0,20]
          user.first_name = auth.info.first_name
          user.picture_url = auth.info.image
        end
      end
    
      def self.new_with_session(params, session)
        super.tap do |user|
          if data = session["devise.facebook_data"]
            user.email = data["info"]["email"] if user.email.blank?
            user.first_name = data["info"]["first_name"] if user.first_name.blank?
            user.last_name = data["info"]["last_name"] if user.last_name.blank?
            user.address = data["info"]["location"] if user.address.blank?
            user.sex = data["extra"]["raw_info"]["gender"] if user.sex.blank?
            user.picture_url = data["info"]["image"]
          end
        end
      end

Then my omniauth_callbacks_controller.rb:

    def facebook
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        @user = User.from_omniauth(request.env["omniauth.auth"])
    
        if @user.persisted?
          debugger
          sign_in_and_redirect root_path, event: :authentication #this will throw if @user is not activated
          set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
        else
          session["devise.facebook_data"] = request.env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
      end

routes.rb:

    Rails.application.routes.draw do
      root 'home#index'
      mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    
      # path_names: configure different path names to overwrite defaults :sign_in, :sign_out, :sign_up,
      #   :password, :confirmation, :unlock.
      #   More route config info here
      #   http://www.rubydoc.info/github/plataformatec/devise/ActionDispatch/Routing/Mapper#devise_for-instance_method
      devise_for :users, module: "users", path: '' , path_names: {sign_up: "register"}
    
      resources :facilities
    end

I tried to follow [this][1] guide and it worked perfectly at some point but I'm guessing the changes I made screwed things up. 

  [1]: https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview

**Comment by raffe90** [comment]
How did you manage this?

**Comment by simkessy** [comment]
I got it working eventually, I don't really remember how.

**Comment by raffe90** [comment]
In case anyone find this error, I got it working with this:

def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted? || @user.save
      debugger
      sign_in_and_redirect root_path, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end

**Comment by jundalisay** [comment]
In my case, it was because my seeded db already had a user with email x@xyz.com so when my FB account (which had the same email of x@xyz.com) tried to login, it found an already existing non-fb user record, so it couldn't create the new FB user record.

**Comment by cweems** [comment]
I had the same issue: there was a unique constraint on the email column of my user model. Omniauth was attempting to add a user, but the duplicate email prevented this.

I ended up changing the `from_omniauth` method in `user.rb`:

```ruby
def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_initialize.tap do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.full_name = auth.info.name
      user.profile_image = auth.info.image
      user.save
    end
end
```

This stackoverflow post was helpful in discussing how to create or update an existing user object: http://stackoverflow.com/questions/18747062/rails-create-or-update-magic

**Comment by dizo1** [comment]
where(email: auth.info.email).first_or_initialize.tap do |user|
this line saved me tonnes of trouble

**Comment by ktdmedia** [comment]
+1000 for "where(email: auth.info.email).first_or_initialize.tap do |user|"
