### ISSUE TITLE
ActionDispatch::Cookies::CookieOverflow with long URLs

### ISSUE THREAD

**Issue by fschwahn** [intridea/omniauth#817]
Hi,
I'm using `omniauth` with `omniauth-facebook` (and `devise`, but I think that's irrelevant for this issue). I'm lately getting redirects with very long URLs from Facebook (I'm not sure why), e.g.:

    https://www.example.com/users/auth/facebook?__tn__=*I&xt=lW0Gh_8up_Ts-r4futl7Ej8Z3ANWpFwZnwkFNEu5TRiLiSTi8jAH3fl1NOPFa3waQwbKIB7wawkjpJJ6a6A9uJGza9tgrotwFsrj4TEmkWnV5zQ_xn30G_kj6WuZS5TzQuWc8uecpLa_bKp8qh8rsogNxyv3gL2TAbO4u6_Ei3bvGV5xaLundNKkX9-aaJoHx8e5RONPcs5ctGpyafaTomF4ZQpmuV_JRfrGAo2oSDAYk6CUIZanLfNFVv0Jns_9-K7CGfh6dbKVjiQ82NKtDxI7PCSMU0jRsAPhITm97PzZJg56PQyf9M4a3x8UvHdjA5ToQZ0Y8UC-N2GTB-f6RlXuUWwnRQYsRixl1gL1BJkUNs5hPiAanl1fdsIKwTiqOXaijlQqiFxrhVCZun76Xqj_RyaXhr85k29O7gdWcXJ_GhgO25tmUBDsvCefoduB4LoA73OXLmfB10aXR84O3uLE4x-AX2pvbOxbYC2XUzVqWzS4lRohvQtFw7jHmJ02VyA-DRtCnE5BguGHXjypw37UjVDpe6tJhKMlStJJh3a54IgSIZEMzszvD_YxaGuzYez-7evcetrt4i2AW5qUqJqcnfWO0xO9_Ha51kyy851DIlsSB6q2Ls4SW5xBaVHUAjJG506hn1r-XoA3v0GwI9j5KsZeSwJQZF2En9yN-21pnDFDi03rg4Xjw3ymE1KkfB-m8FGvsfMkKTrFJGLTOSWMN_-tmHb4Tf8EWnJYX8lqQ2NO9KSYMof57ZsTR0b4pb_HCTfyoIabTp27IB_lX_C6ZtwfPrJzBHaS6pDzF201g_BnwFQbrgyDvodz8vBJzGn3eEWcGU8TjUE3mTT8MRb-d5Ez3SajrHk3XdktioO_IDn9EGzJCEe0Xd6CvINzlynVdoxd7WbMaPD7XSr-GJ5oHMxWgxBA61pbjmeFLJCj-wNqUfYV0U0dgS4vKpeOxBUXAyYtIfnK9W9K-_KndS7m0J6zV7Q3PR18wr6Im6hE1VerIxAzgmDL6LAFjrZ3_Fqt7ExSRLO7qHhq4J3K5MMCe6o74vV9229Y7bmzlyH6B_JHJFl53mNl8D8ItEtaFTphQK8ewIiCpGgru7gsbSdvNAdouZENnS1XlvpuvXOIH1ITGS_nwpdcXx3LMF7bjB4jyrPvvLoxkPW8ED0fp-Ozuy_JUEu2p1W3wiQ5YpkGgv-qJvFAYeAgEAam_SF_vYhcFIjX7Q_arM6G8VmSb8Kehfbz4-q7DtJq_1s6HMZIVlo3CXfk9VVA_kPnWkjhVjMoEqy9K8istqGcZ3TtvyVaDSfhDUWrbIyGQe5ddBkhhzkfyFzh0gLuIUf6Zr6r6IUy8CLWpCamTHxVdmTmtZ5_q5bf1YvmvWcpm8r73CizLZCm2XdmtNFUgh8hKs8lL3nIY3LBlQtzLQ3PqAEiAmCTNvh1xoWVxSf9HLqNKfSQwXwJSsYSZKfMZD5klGdod7PmviuB67DVU7IJYJWDTUwTYEPt3lZM7VTle_FRXCEuDp4KszKlEl32nVr9jdumuSm_qXkC__LjkrlrHkkK3uYbaUFEjerCLc-Dlq-50bBYbhO4HrRjSWvP7zaDGoYlOmjpLOYVnv5kOQI-0QhoT9jgQb8gWZDbi2CXMBJ2CC0DK-bbOT7MFQtq7BjWZcNXpge-NXtT0FQzGeNvvsueKoqIFdXTPJbgeJ_qcWEEwj9YJQd3Pv8wtMw0WTxAdIystlbx4uqtyCbPdWvIAczva7Mokt4o9UkpUKvz-Ebt_wXJkraHyARUpai0IndzEqZcgxKzzxTi1ymRV-BOSmkntdXCvF5UvAoSs6V6Lsj_o3bD2HVrlIm0Um4pfh6BpJEd1RIB-mcxESpL52ABtko7Bz_c97pUrqEE03P.3JEm8B8qp7oZ-VORrwCeEl7jOgqclsHCNhISFk1ta_MQNjbkSQT1yGbDhjnBcQTUKeXRdlKfxZD1j4shkvvQUC5QrOhWjXxu9WpUzL9LTlEQY26ghkbTvDwEH0_z4faZdW-N01osxL5ldASJSo1y-lEpUyJowQo9Ofp23qlNMGjkideujntvpEOMJ73Y05OHMMOgvI4gXNerTHbBmUSZaXQGOX4PemRF8WieQtG_WHzYmvrRx-sFn4a6bCZNcnSsVaoW1FS3pY0IP5GuVGETDjya4_gH3290npxuW2osHvfhZO4XnIsNQC4IEel8xZEJJMW3lq4RvdM7PmS_jHfA86E89cBU5p2inxFjEDtUAZ9_0pPBuhVw_39kVxTes-sMwvE6c7cKqmWv&mac=hSHQ_TQsq8AVVx2K&sig=99612

This leads to a `ActionDispatch::Cookies::CookieOverflow`-exceptions. I looked at the logs, and I'm seeing `INFO -- omniauth: (facebook) Request phase initiated` right before the exception is raised. My guess is that the line https://github.com/intridea/omniauth/blob/master/lib/omniauth/strategy.rb#L201 is the culprit, saving the params in the session.

Do you have any idea what can be done about this problem?

Thank you for your time!

**Comment by fschwahn** [comment]
Ok, so the issue is actually similar, but not quite what I described above:

In line https://github.com/intridea/omniauth/blob/master/lib/omniauth/strategy.rb#L213 the referer is saved, and the referer is such an extremely long url generated by Facebook. When it is saved, it is too big for the cookie store, and the exception is raised.
I was able to fix the problem by using the `before_request_phase`-hook to set the `HTTP_REFERER` to nil if it is too large.

This is probably not an omniauth-issue, as I'd guess this only happens when the session store is a cookie.

**Comment by dgilperez** [comment]
I'm seeing such random errors as well. How did you solve them? Activerecord session store was extracted from Rails and seems to be not very actively maintained, so I'd definitely like to stick to the default (encrypted) cookie store. 

Is there any commonly accepted workaround for this issues?

**Comment by Bram9205** [comment]
@fschwahn I have the same problem and would like to try your solution.
Can you tell me where to place the before_request_phase hook?

**Comment by fschwahn** [comment]
@Bram9205 that's basically what I did, and it works for me.

**Comment by Bram9205** [comment]
Thanks for your reply. 
Unfortunately that solution did not work for me so I ended up fixing it by using Active Record Session Store, as explained here: http://stackoverflow.com/a/18581914
